// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using passapi.data;

#nullable disable

namespace passapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241123233745_changeRankToString")]
    partial class changeRankToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("passapi.models.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CustomerId")
                        .HasColumnType("double precision");

                    b.Property<string>("FifthGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FourthGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Held")
                        .HasColumnType("text");

                    b.Property<int>("HewittPercentile")
                        .HasColumnType("integer");

                    b.Property<int>("NationalPercentile")
                        .HasColumnType("integer");

                    b.Property<string>("OverallRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PercentCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("RawScore")
                        .HasColumnType("integer");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<int>("RitScore")
                        .HasColumnType("integer");

                    b.Property<string>("SecondGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeventhGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SixthGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StudentId")
                        .HasColumnType("double precision");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TestId")
                        .HasColumnType("double precision");

                    b.Property<string>("ThirdGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
