// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using passapi.data;

#nullable disable

namespace passapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("passapi.models.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("FifthGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FourthGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Held")
                        .HasColumnType("text");

                    b.Property<int>("HewittPercentile")
                        .HasColumnType("integer");

                    b.Property<int>("NationalPercentile")
                        .HasColumnType("integer");

                    b.Property<string>("OverallRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PercentCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("RawScore")
                        .HasColumnType("integer");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<int>("RitScore")
                        .HasColumnType("integer");

                    b.Property<string>("SecondGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeventhGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SixthGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<string>("ThirdGoalRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
